Massive improvements to error handling in "gentoo/_system".
	* In particular, no more compounded bind mounts...
	* Plus, now it looks way prettier!

diff --git a/gentoo/_system b/gentoo/_system
--- a/gentoo/_system
+++ b/gentoo/_system
@@ -285,6 +285,18 @@ function print_info {
 		echo -en "${OTHER}"
 		printf "~%.0s" {1..80}
 		echo -en "${RESET}\n"
+	elif [[ ${1} == "title" ]]; then
+		echo -en "${NOTES}"
+		echo -en ">>> GARYOS BUILD SCRIPT <<<"
+		echo -en "${RESET}\n"
+	elif [[ ${1} == "success" ]]; then
+		echo -en "${TITLE}"
+		echo -en ">>> GARYOS BUILD SCRIPT: SUCCESS! <<<"
+		echo -en "${RESET}\n"
+	elif [[ ${1} == "error" ]]; then
+		echo -en "${ERROR}"
+		echo -en ">>> GARYOS BUILD SCRIPT: FAILURE! <<<"
+		echo -en "${RESET}\n"
 	elif [[ ${1} == "usage" ]]; then
 		declare PRINTF=
 		PRINTF+="${TITLE}%-45.45s${RESET} "
@@ -481,6 +493,35 @@ function kernel_cpu {
 
 ################################################################################
 
+trap "EXIT 1" SIGHUP SIGINT SIGKILL SIGTERM
+
+function EXIT {
+	declare EXIT="0"
+	if [[ ${1} != 0 ]]; then
+		if [[ ${1} == -1 ]]; then
+			EXIT="1" && shift
+		else
+			EXIT="${1}" && shift
+			mount_dev_dirs -u || EXIT -1
+		fi
+		if [[ -z ${QUIET} ]]; then
+			print_info marker
+			print_info error
+			print_info marker
+		fi
+	else
+		if [[ -z ${QUIET} ]]; then
+			print_info marker
+			print_info success
+			print_info marker
+		fi
+	fi
+	exit ${EXIT}
+}
+
+########################################
+
+print_info marker;	print_info title
 print_info marker;	print_info usage
 print_info marker;	print_info starter
 print_info marker;	print_info environment;	clear_environment
@@ -491,24 +532,24 @@ print_info marker
 if [[ -n ${DEBUG} ]]; then
 	if ${DO_CHROOT}; then
 		set -x
-		safe_env ${MYSELF} ${DEBUG_OPT} ${TOOR} "${@}" || exit 1
+		safe_env ${MYSELF} ${DEBUG_OPT} ${TOOR} "${@}" || EXIT 1
 	fi
-	exit 0
+	EXIT 0
 fi
 
 ################################################################################
 
 if [[ ${1} == -z ]]; then
 	shift
-	mount_dev_dirs -u	|| exit 1
-	exit 0
+	mount_dev_dirs -u || EXIT -1
+	EXIT 0
 fi
 
 ########################################
 
 if [[ ${1} == -s ]]; then
 	shift
-	mount_dev_dirs							|| exit 1
+	mount_dev_dirs							|| EXIT 1
 	if [[ ${1} == -g ]]; then
 		shift
 		expect_wrapper emerge ${_ASK} \
@@ -516,41 +557,41 @@ if [[ ${1} == -s ]]; then
 			--emptytree \
 			--tree \
 			--unordered-display \
-			\@system \@world				|| exit 1
+			\@system \@world				|| EXIT 1
 	elif [[ ${1} == -e ]]; then
 		shift
-		expect_wrapper emerge ${_ASK} "${@}"			|| exit 1
+		expect_wrapper emerge ${_ASK} "${@}"			|| EXIT 1
 	else
-		safe_env /usr/bin/env bash -o vi ${@:+-c \"${@}\"}	|| exit 1
+		safe_env /usr/bin/env bash -o vi ${@:+-c \"${@}\"}	|| EXIT 1
 	fi
-	mount_dev_dirs -u						|| exit 1
-	exit 0
+	mount_dev_dirs -u						|| EXIT 1
+	EXIT 0
 fi
 
 ########################################
 
 if [[ ${1} == -o ]]; then
 #>>>	shift
-	if ${DO_CHROOT}; then
-		FILE="${SETDIR}/${FUNDIR}"
-	else	FILE="${ETCDIR}"
+	if ${DO_CHROOT}
+		then FILE="${SETDIR}/${FUNDIR}"
+		else FILE="${ETCDIR}"
 	fi
-	FILE="$(${LS} -d ${FILE}/${OVLDIR}/*/${2} | ${SED} "s|^${FILE}/${OVLDIR}/||g")"
+	FILE="$(${LS} -d ${FILE}/${LAYDIR}/*/${2} | ${SED} "s|^${FILE}/${LAYDIR}/||g")"
 	NEXT="$(dirname ${FILE})"
 	if ${DO_CHROOT}; then
-#>>>		safe_env ${MYSELF} ${QUIET_OPT} ${TOOR} -r									|| exit 1
-		${_SELF} ${QUIET_OPT} ${TOOR} -r										|| exit 1
-		${MKDIR}	${TARGET}${ETCDIR}/${OVLDIR}/${NEXT}								|| exit 1
-		${RSYNC_U}	${TARGET}${REPDIR}/kits/*/${FILE}/		${SETDIR}/${FUNDIR}/${OVLDIR}/${FILE}.src	|| exit 1
-		${RSYNC_U}	${SETDIR}/${FUNDIR}/${OVLDIR}/${FILE}/		${TARGET}${ETCDIR}/${OVLDIR}/${FILE}		|| exit 1
-		safe_env ${MYSELF} ${QUIET_OPT} ${TOOR} "${@}"									|| exit 1
-		${RSYNC_U}	${TARGET}${ETCDIR}/${OVLDIR}/${FILE}/Manifest	${SETDIR}/${FUNDIR}/${OVLDIR}/${FILE}/		|| exit 1
-		${RSYNC_U}	${TARGET}${ETCDIR}/${OVLDIR}/.review.txt	${SETDIR}/${FUNDIR}/${OVLDIR}/			|| exit 1
+#>>>		safe_env ${MYSELF} ${QUIET_OPT} ${TOOR} -r									|| EXIT 1
+		${_SELF} ${QUIET_OPT} ${TOOR} -r										|| EXIT 1
+		${MKDIR}	${TARGET}${ETCDIR}/${LAYDIR}/${NEXT}								|| EXIT 1
+		${RSYNC_U}	${TARGET}${REPDIR}/kits/*/${FILE}/		${SETDIR}/${FUNDIR}/${LAYDIR}/${FILE}.src	|| EXIT 1
+		${RSYNC_U}	${SETDIR}/${FUNDIR}/${LAYDIR}/${FILE}/		${TARGET}${ETCDIR}/${LAYDIR}/${FILE}		|| EXIT 1
+		safe_env ${MYSELF} ${QUIET_OPT} ${TOOR} "${@}"									|| EXIT 1
+		${RSYNC_U}	${TARGET}${ETCDIR}/${LAYDIR}/${FILE}/Manifest	${SETDIR}/${FUNDIR}/${LAYDIR}/${FILE}/		|| EXIT 1
+		${RSYNC_U}	${TARGET}${ETCDIR}/${LAYDIR}/.review.txt	${SETDIR}/${FUNDIR}/${LAYDIR}/			|| EXIT 1
 	else
-		ebuild		${ETCDIR}/${OVLDIR}/${FILE}/*.ebuild digest							|| exit 1
-		(cd		${ETCDIR}/${OVLDIR} && ./.review)								|| exit 1
+		ebuild		${ETCDIR}/${LAYDIR}/${FILE}/*.ebuild digest							|| EXIT 1
+		(cd		${ETCDIR}/${LAYDIR} && ./.review)								|| EXIT 1
 	fi
-	exit 0
+	EXIT 0
 fi
 
 ########################################
@@ -558,12 +599,12 @@ fi
 if [[ ${1} == -l ]]; then
 #>>>	shift
 	if ${DO_CHROOT}; then
-		safe_env ${MYSELF} ${QUIET_OPT} ${TOOR} "${@}" || exit 1
-		exit 0
+		safe_env ${MYSELF} ${QUIET_OPT} ${TOOR} "${@}" || EXIT 1
+		EXIT 0
 	fi
 	shift
 	if [[ -z ${1} ]]; then
-		exit 0
+		EXIT 0
 	elif [[ ${1} == +([0-9]) ]]; then
 		echo -en "https://bugs.gentoo.org/show_bug.cgi?id=${1}"
 	else
@@ -582,7 +623,7 @@ if [[ ${1} == -l ]]; then
 			${LL} ${FILE}
 		fi
 	fi
-	exit 0
+	EXIT 0
 fi
 
 ########################################
@@ -590,8 +631,8 @@ fi
 if [[ ${1} == -p ]]; then
 #>>>	shift
 	if ${DO_CHROOT}; then
-		safe_env ${MYSELF} ${QUIET_OPT} ${TOOR} "${@}" || exit 1
-		exit 0
+		safe_env ${MYSELF} ${QUIET_OPT} ${TOOR} "${@}" || EXIT 1
+		EXIT 0
 	fi
 	shift
 	${LL} -d ${WRKDIR}
@@ -612,9 +653,9 @@ if [[ ${1} == -p ]]; then
 		done |
 			${SED} "s|[ ]*$||g"			1>&2
 		echo -en "\"\n"					1>&2
-		exit 1
+		EXIT 1
 	fi
-	exit 0
+	EXIT 0
 fi
 
 ################################################################################
@@ -624,31 +665,31 @@ if [[ ${1} == -[0/12] ]]; then
 	date --iso=seconds >${TARGET}${GENDIR}.log 2>&1
 fi
 
-if [[ ${1} == -0 ]]; then shift; ${_SELF} ${TOOR} -n -a -b -k	-i 2>&1 | tee --append ${TARGET}${GENDIR}.log | prompt -c	; exit 0; fi
-if [[ ${1} == -/ ]]; then shift; ${_SELF} ${TOOR} -a		-i 2>&1 | tee --append ${TARGET}${GENDIR}.log | prompt -c	; exit 0; fi
-if [[ ${1} == -1 ]]; then shift; ${_SELF} ${TOOR} -a -b		-i 2>&1 | tee --append ${TARGET}${GENDIR}.log | prompt -c	; exit 0; fi
-if [[ ${1} == -2 ]]; then shift; ${_SELF} ${TOOR} -c		-i								; exit 0; fi
+if [[ ${1} == -0 ]]; then shift; ${_SELF} ${TOOR} -n -a -b -k	-i 2>&1 | tee --append ${TARGET}${GENDIR}.log | prompt -c	; exit ${PIPESTATUS[0]}; fi
+if [[ ${1} == -/ ]]; then shift; ${_SELF} ${TOOR} -a		-i 2>&1 | tee --append ${TARGET}${GENDIR}.log | prompt -c	; exit ${PIPESTATUS[0]}; fi
+if [[ ${1} == -1 ]]; then shift; ${_SELF} ${TOOR} -a -b		-i 2>&1 | tee --append ${TARGET}${GENDIR}.log | prompt -c	; exit ${PIPESTATUS[0]}; fi
+if [[ ${1} == -2 ]]; then shift; ${_SELF} ${TOOR} -c		-i								; exit ${PIPESTATUS[0]}; fi
 
 ########################################
 
 if [[ ${1} == -r ]]; then
 	shift
-	${MKDIR}						${TARGET}${ARCDIR}				|| exit 1
-	${MKDIR}						${TARGET}${HOMELY}				|| exit 1
+	${MKDIR}						${TARGET}${ARCDIR}				|| EXIT 1
+	${MKDIR}						${TARGET}${HOMELY}				|| EXIT 1
 	if [[ -f ${SETDIR}/.bashrc ]]
-		then ${RSYNC_U} --copy-links ${SETDIR}/.bashrc	${TARGET}${HOMELY}/				|| exit 1
-		else ${RSYNC_U} --copy-links ${HOME}/.bashrc	${TARGET}${HOMELY}/				|| exit 1
+		then ${RSYNC_U} --copy-links ${SETDIR}/.bashrc	${TARGET}${HOMELY}/				|| EXIT 1
+		else ${RSYNC_U} --copy-links ${HOME}/.bashrc	${TARGET}${HOMELY}/				|| EXIT 1
 	fi
-	${RSYNC_U} ${SETDIR}/${FUNDIR}/				${TARGET}${ARCDIR}/${FUNDIR}			|| exit 1
-	${RSYNC_U} ${SETDIR}/${LINDIR}/				${TARGET}${ARCDIR}/${LINDIR}			|| exit 1
-	${RSYNC_C} ${SETDIR}/${FUNDIR}/[a-z_]*			${TARGET}${ETCDIR}/				|| exit 1
-	${RSYNC_U} ${SETDIR}/${FUNDIR}/${LAYDIR}/		${TARGET}${ETCDIR}/${LAYDIR}			|| exit 1
-	${LN} ${ETCDIR}/${OVLDIR}/overlay.conf			${TARGET}${ETCDIR}/repos.conf/			|| exit 1
+	${RSYNC_U} ${SETDIR}/${FUNDIR}/				${TARGET}${ARCDIR}/${FUNDIR}			|| EXIT 1
+	${RSYNC_U} ${SETDIR}/${LINDIR}/				${TARGET}${ARCDIR}/${LINDIR}			|| EXIT 1
+	${RSYNC_C} ${SETDIR}/${FUNDIR}/[a-z_]*			${TARGET}${ETCDIR}/				|| EXIT 1
+	${RSYNC_U} ${SETDIR}/${FUNDIR}/${LAYDIR}/		${TARGET}${ETCDIR}/${LAYDIR}			|| EXIT 1
+	${LN} ${ETCDIR}/${LAYDIR}/overlay.conf			${TARGET}${ETCDIR}/repos.conf/			|| EXIT 1
 	if [[ ${1} == -w ]]; then
 		shift
-		safe_env					${MYSELF} ${QUIET_OPT} ${TOOR} ${AUTO} -w	|| exit 1
+		safe_env					${MYSELF} ${QUIET_OPT} ${TOOR} ${AUTO} -w	|| EXIT 1
 	fi
-	exit 0
+	EXIT 0
 fi
 
 ########################################
@@ -656,17 +697,17 @@ fi
 if [[ ${1} == -i ]]; then
 	shift
 	if [[ ! -d ${TARGET}/boot ]]; then
-		${MKDIR}				${TARGET}${ARCDIR}						|| exit 1
-		${RSYNC_U} ${SOURCE}/*funtoo*		${TARGET}${ARCDIR}/						|| exit 1
-#>>>		tar -pvvx --xz -C ${TARGET} -f		$(ls -t ${TARGET}${ARCDIR}/stage3-*i686*funtoo*.tar.xz		| head -n1) || exit 1
-		tar -pvvx --xz -C ${TARGET} -f		$(ls -t ${TARGET}${ARCDIR}/stage3-*core2_64*funtoo*.tar.xz	| head -n1) || exit 1
+		${MKDIR}				${TARGET}${ARCDIR}						|| EXIT 1
+		${RSYNC_U} ${SOURCE}/*funtoo*		${TARGET}${ARCDIR}/						|| EXIT 1
+#>>>		tar -pvvx --xz -C ${TARGET} -f		$(ls -t ${TARGET}${ARCDIR}/stage3-*i686*funtoo*.tar.xz		| head -n1) || EXIT 1
+		tar -pvvx --xz -C ${TARGET} -f		$(ls -t ${TARGET}${ARCDIR}/stage3-*core2_64*funtoo*.tar.xz	| head -n1) || EXIT 1
 	fi
-	mount_dev_dirs													|| exit 1
-#>>>	safe_env					${MYSELF} ${QUIET_OPT} ${TOOR} ${AUTO} -r			|| exit 1
-							${_SELF} ${QUIET_OPT} ${TOOR} ${AUTO} -r			|| exit 1
+	mount_dev_dirs													|| EXIT 1
+#>>>	safe_env					${MYSELF} ${QUIET_OPT} ${TOOR} ${AUTO} -r			|| EXIT 1
+							${_SELF} ${QUIET_OPT} ${TOOR} ${AUTO} -r			|| EXIT 1
 	if [[ ! -d ${TARGET}${REPDIR} ]] && [[ -d ${GITDIR} ]]; then
-		${MKDIR}				${TARGET}${REPDIR}{,.git}					|| exit 1
-		${RSYNC_U} ${GITDIR}/			${TARGET}${REPDIR}.git						|| exit 1
+		${MKDIR}				${TARGET}${REPDIR}{,.git}					|| EXIT 1
+		${RSYNC_U} ${GITDIR}/			${TARGET}${REPDIR}.git						|| EXIT 1
 	fi
 	declare META_FULL="${TARGET}${REPDIR}.git.tar.xz"
 	declare META_ONLY="${TARGET}${REPDIR}.tar.xz"
@@ -675,59 +716,59 @@ if [[ ${1} == -i ]]; then
 		then
 			FILE="$(dirname ${TARGET}${REPDIR})"
 			NEXT="$(basename ${REPDIR})"
-			tar -cvv --xz -C ${FILE} -f	${META_FULL}	${NEXT}{,.git}					|| exit 1
-			tar -cvv --xz -C ${FILE} -f	${META_ONLY}	${NEXT}						|| exit 1
+			tar -cvv --xz -C ${FILE} -f	${META_FULL}	${NEXT}{,.git}					|| EXIT 1
+			tar -cvv --xz -C ${FILE} -f	${META_ONLY}	${NEXT}						|| EXIT 1
 		else
-			${SETDIR}/${FUNDIR}/${FUNKIT}	${TARGET}${REPDIR} ${FUNTOO}					|| exit 1
+			${SETDIR}/${FUNDIR}/${FUNKIT}	${TARGET}${REPDIR} ${FUNTOO}					|| EXIT 1
 		fi
 	fi
-	${SETDIR}/${FUNDIR}/${FUNKIT}			${TARGET}${REPDIR} ${FUNTOO}					|| exit 1
-	safe_env					${MYSELF} ${QUIET_OPT} ${TOOR} ${AUTO} -w			|| exit 1
+	${SETDIR}/${FUNDIR}/${FUNKIT}			${TARGET}${REPDIR} ${FUNTOO}					|| EXIT 1
+	safe_env					${MYSELF} ${QUIET_OPT} ${TOOR} ${AUTO} -w			|| EXIT 1
 	if ${_BLD}; then
 		if [[ -n ${_NEW} ]]; then
-			expect_wrapper			emerge ${_ASK} expect						|| exit 1
-			safe_env			${MYSELF} ${QUIET_OPT} ${TOOR} ${AUTO} -f			|| exit 1
-			expect_wrapper			emerge ${_ASK} --deep --newuse --update \@system		|| exit 1
+			expect_wrapper			emerge ${_ASK} expect						|| EXIT 1
+			safe_env			${MYSELF} ${QUIET_OPT} ${TOOR} ${AUTO} -f			|| EXIT 1
+			expect_wrapper			emerge ${_ASK} --deep --newuse --update \@system		|| EXIT 1
 		else
-			expect_wrapper			emerge ${_ASK} --emptytree \@system \@world			|| exit 1
+			expect_wrapper			emerge ${_ASK} --emptytree \@system \@world			|| EXIT 1
 		fi
 	fi
 	if ${_KRN}; then for FILE in ${KERNEL}; do
-		${RM}					${TARGET}/usr/src/linux						|| exit 1
-		${LN} linux-${FILE}-gentoo		${TARGET}/usr/src/linux						|| exit 1
-		expect_wrapper				emerge ${_ASK} genkernel =gentoo-sources-${FILE}		|| exit 1
+		${RM}					${TARGET}/usr/src/linux						|| EXIT 1
+		${LN} linux-${FILE}-gentoo		${TARGET}/usr/src/linux						|| EXIT 1
+		expect_wrapper				emerge ${_ASK} genkernel =gentoo-sources-${FILE}		|| EXIT 1
 		${RSYNC_U}				${SETDIR}/${LINDIR}/config-gentoo64-${FILE}			\
-							${TARGET}${ARCDIR}/config-gentoo64-${FILE}			|| exit 1
-		kernel_cpu 				${TARGET}${ARCDIR}/config-gentoo64-${FILE}			|| exit 1
+							${TARGET}${ARCDIR}/config-gentoo64-${FILE}			|| EXIT 1
+		kernel_cpu 				${TARGET}${ARCDIR}/config-gentoo64-${FILE}			|| EXIT 1
 		declare GENKERNEL_OPTS="--loglevel=5 --bootloader=grub --install --symlink"
 		if [[ -z ${AUTO} ]]; then
-			expect_wrapper			genkernel ${GENKERNEL_OPTS} kernel --menuconfig			|| exit 1
+			expect_wrapper			genkernel ${GENKERNEL_OPTS} kernel --menuconfig			|| EXIT 1
 		else
 			expect_wrapper			genkernel ${GENKERNEL_OPTS} kernel				\
-							--kernel-config=${ARCDIR}/config-gentoo64-${FILE}		|| exit 1
+							--kernel-config=${ARCDIR}/config-gentoo64-${FILE}		|| EXIT 1
 		fi
-#>>>		FILE="kernel-genkernel-x86-${FILE}-gentoo"								|| exit 1
-		FILE="kernel-genkernel-x86_64-${FILE}-gentoo"								|| exit 1
+#>>>		FILE="kernel-genkernel-x86-${FILE}-gentoo"								|| EXIT 1
+		FILE="kernel-genkernel-x86_64-${FILE}-gentoo"								|| EXIT 1
 		if [[ -z ${_GOS} ]]; then
-			${RM}				${TARGET}/boot/_cur						|| exit 1
-			${LN} ${FILE}			${TARGET}/boot/_cur						|| exit 1
-			${RM}				${TARGET}/boot/_new						|| exit 1
-			${LN} kernel			${TARGET}/boot/_new						|| exit 1
-			${RM}				${TARGET}/boot/_old						|| exit 1
-			${LN} kernel.old		${TARGET}/boot/_old						|| exit 1
+			${RM}				${TARGET}/boot/_cur						|| EXIT 1
+			${LN} ${FILE}			${TARGET}/boot/_cur						|| EXIT 1
+			${RM}				${TARGET}/boot/_new						|| EXIT 1
+			${LN} kernel			${TARGET}/boot/_new						|| EXIT 1
+			${RM}				${TARGET}/boot/_old						|| EXIT 1
+			${LN} kernel.old		${TARGET}/boot/_old						|| EXIT 1
 			{ [[ -L				${TARGET}/boot/kernel.old ]] ||
-			${LN} ${FILE}			${TARGET}/boot/kernel.old; }					|| exit 1
+			${LN} ${FILE}			${TARGET}/boot/kernel.old; }					|| EXIT 1
 		fi
 	done; fi
 	declare KERNEL="$(cd ${TARGET}/boot; ls kernel-debian-sources-*		2>/dev/null | sort | tail -n1)"
 	declare INITRD="$(cd ${TARGET}/boot; ls initramfs-debian-sources-*	2>/dev/null | sort | tail -n1)"
 	if [[ -n ${KERNEL} ]]; then
-		${RM}					${TARGET}/boot/_kernel						|| exit 1
-		${LN} ${KERNEL}				${TARGET}/boot/_kernel						|| exit 1
+		${RM}					${TARGET}/boot/_kernel						|| EXIT 1
+		${LN} ${KERNEL}				${TARGET}/boot/_kernel						|| EXIT 1
 	fi
 	if [[ -n ${INITRD} ]]; then
-		${RM}					${TARGET}/boot/_initrd						|| exit 1
-		${LN} ${INITRD}				${TARGET}/boot/_initrd						|| exit 1
+		${RM}					${TARGET}/boot/_initrd						|| EXIT 1
+		${LN} ${INITRD}				${TARGET}/boot/_initrd						|| EXIT 1
 	fi
 	if ${_CFG}; then
 		${MAKEIT}_config											|| EXIT 1
@@ -735,10 +776,10 @@ if [[ ${1} == -i ]]; then
 			${RSYNC_U} ${CFGSCR}		${TARGET}/${ARCDIR}/$(basename ${CFGSCR})			|| EXIT 1
 			safe_env			${ARCDIR}/$(basename ${CFGSCR})					|| EXIT 1
 		fi
-	safe_env					${MYSELF} ${QUIET_OPT} ${TOOR} ${AUTO} -f			|| exit 1
-	safe_env					${MYSELF} ${QUIET_OPT} ${TOOR} ${AUTO} -u			|| exit 1
-	mount_dev_dirs -u												|| exit 1
-	exit 0
+	safe_env					${MYSELF} ${QUIET_OPT} ${TOOR} ${AUTO} -f			|| EXIT 1
+	safe_env					${MYSELF} ${QUIET_OPT} ${TOOR} ${AUTO} -u			|| EXIT 1
+	mount_dev_dirs -u												|| EXIT 1
+	EXIT 0
 fi
 
 ################################################################################
@@ -758,11 +799,11 @@ if [[ ${1} == -w ]]; then
 		-e "s|[#][{]GSUB[}]|${GSUB}|g" \
 		-e "s|[#][{]GOPT[}]|${GOPT}|g" \
 		${ETCDIR}/make.conf
-	ego profile arch ${EARC}	|| exit 1
-	ego profile subarch ${ESUB}	|| exit 1
-#>>>	ego profile build stable	|| exit 1	# ERROR: build stable is not available. Can't set. Available names: {'current'}
-	ego profile build current	|| exit 1
-	ego profile flavor desktop	|| exit 1
+	ego profile arch ${EARC}	|| EXIT 1
+	ego profile subarch ${ESUB}	|| EXIT 1
+#>>>	ego profile build stable	|| EXIT 1	# ERROR: build stable is not available. Can't set. Available names: {'current'}
+	ego profile build current	|| EXIT 1
+	ego profile flavor desktop	|| EXIT 1
 	ego profile show
 	locale-gen
 	gcc-config $(gcc-config --list-profiles | awk '{print $2;}' | sort -n | tail -n1)
@@ -788,34 +829,34 @@ if [[ ${1} == -w ]]; then
 	$(for NEXT in ${LINPKG}; do
 		echo "${NEXT}"	>>/var/lib/portage/world
 	done)
-	exit 0
+	EXIT 0
 fi
 
 ########################################
 
 if [[ ${1} == -u ]]; then
 	shift
-	safe_env ${_SELF} ${QUIET_OPT} ${TOOR} ${AUTO} -w			|| exit 1
-	expect_wrapper emerge ${_ASK} --deep --newuse --update \@system \@world	|| exit 1
-	safe_env ${_SELF} ${QUIET_OPT} ${TOOR} ${AUTO} -p			|| exit 1
+	safe_env ${_SELF} ${QUIET_OPT} ${TOOR} ${AUTO} -w			|| EXIT 1
+	expect_wrapper emerge ${_ASK} --deep --newuse --update \@system \@world	|| EXIT 1
+	safe_env ${_SELF} ${QUIET_OPT} ${TOOR} ${AUTO} -p			|| EXIT 1
 #>>>	https://gitweb.gentoo.org/repo/gentoo.git/commit/?id=b7a4174e075a922a255c0ff4a6ebd4f6d0437c61
 #>>>	if [[ -n "$(which python-updater 2>/dev/null)" ]]; then
-#>>>		expect_wrapper python-updater					|| exit 1
+#>>>		expect_wrapper python-updater					|| EXIT 1
 #>>>	fi
 	if [[ -n "$(which perl-cleaner 2>/dev/null)" ]]; then
-		expect_wrapper perl-cleaner --all				|| exit 1
+		expect_wrapper perl-cleaner --all				|| EXIT 1
 	fi
 	if [[ -n "$(which haskell-updater 2>/dev/null)" ]]; then
-		expect_wrapper haskell-updater --all				|| exit 1
+		expect_wrapper haskell-updater --all				|| EXIT 1
 	fi
-	expect_wrapper emerge ${_ASK} \@module-rebuild --exclude "${LINPKG}"	|| exit 1
-	expect_wrapper emerge ${_ASK} \@preserved-rebuild			|| exit 1
-	expect_wrapper emerge ${_ASK} --depclean				|| exit 1
-	expect_wrapper revdep-rebuild --ignore					|| exit 1
-	expect_wrapper emaint --fix all						|| exit 1
-	expect_wrapper eclean --verbose distfiles				|| exit 1
-	expect_wrapper eclean --verbose packages				|| exit 1
-	expect_wrapper dispatch-conf						|| exit 1
+	expect_wrapper emerge ${_ASK} \@module-rebuild --exclude "${LINPKG}"	|| EXIT 1
+	expect_wrapper emerge ${_ASK} \@preserved-rebuild			|| EXIT 1
+	expect_wrapper emerge ${_ASK} --depclean				|| EXIT 1
+	expect_wrapper revdep-rebuild --ignore					|| EXIT 1
+	expect_wrapper emaint --fix all						|| EXIT 1
+	expect_wrapper eclean --verbose distfiles				|| EXIT 1
+	expect_wrapper eclean --verbose packages				|| EXIT 1
+	expect_wrapper dispatch-conf						|| EXIT 1
 
 ########################################
 
@@ -823,13 +864,13 @@ elif [[ ${1} != -! ]]; then
 	if [[ ${1} != -f ]]; then
 		print_info update
 		declare GIT="$(which git)"
-#>>>		expect_wrapper emerge --ask=n --verbose --sync				|| exit 1
-		expect_wrapper ego sync							|| exit 1
-		${SETDIR}/${FUNDIR}/${FUNKIT} ${REPDIR} ${1}				|| exit 1
+#>>>		expect_wrapper emerge --ask=n --verbose --sync				|| EXIT 1
+		expect_wrapper ego sync							|| EXIT 1
+		${SETDIR}/${FUNDIR}/${FUNKIT} ${REPDIR} ${1}				|| EXIT 1
 		for FILE in ${REPDIR}/kits/*kit; do
 			echo -en "egencache: ${FILE}\n"
 			expect_wrapper egencache --repo "$(basename ${FILE})"		\
-				--update-use-local-desc					#>>> || exit 1
+				--update-use-local-desc					#>>> || EXIT 1
 		done
 	fi
 	if [[ -z ${1} ]] || [[ ${1} == -f ]]; then
@@ -866,11 +907,11 @@ elif [[ ${1} != -! ]]; then
 		done
 		${RM} ${DSTDIR}.log							1>&2
 		if ! ${FILE}; then
-			exit 1;
+			EXIT 1
 		fi
 	fi
 	if [[ -n ${1} ]]; then
-		exit 0
+		EXIT 0
 	fi
 fi
 
@@ -905,7 +946,7 @@ if [[ -n "$(diff ${GENDIR}/+okay ${GENDIR}/+okay.okay 2>/dev/null)" ]]; then
 	cat ${GENDIR}/+okay
 fi
 
-exit 0
+EXIT 0
 ################################################################################
 # end of file
 ################################################################################
